services:
  firewallet:
    image: git.woodburn.au/nathanwoodburn/firewallet-hsd:latest
    ports:
      - "5000:5000"
    volumes:
      - hsd_data:/app/hsd_data
      - user_data:/app/user_data

volumes:
  hsd_data:
  user_data:
